"""Shared tensor layout constants for diffusion tracking integration."""

NUM_JOINTS = 29
ROOT_QUAT_DIM = 4
ROOT_POS_DIM = 3
MOTION_FRAME_DIM = NUM_JOINTS + NUM_JOINTS + ROOT_QUAT_DIM + ROOT_POS_DIM

DEFAULT_HISTORY_LEN = 20
DEFAULT_COMMAND_HORIZON = 10

JOINT_POS_SLICE = slice(0, NUM_JOINTS)
JOINT_VEL_SLICE = slice(NUM_JOINTS, NUM_JOINTS * 2)
ROOT_QUAT_SLICE = slice(NUM_JOINTS * 2, NUM_JOINTS * 2 + ROOT_QUAT_DIM)
ROOT_POS_SLICE = slice(NUM_JOINTS * 2 + ROOT_QUAT_DIM, MOTION_FRAME_DIM)

SONIC_JOINT_COMMAND_DIM = NUM_JOINTS * 2
SONIC_ROT6_DIM = 6
SONIC_FRAME_COMMAND_DIM = SONIC_JOINT_COMMAND_DIM + SONIC_ROT6_DIM
